Repository GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator, pull requests merged in 2023-07, with the labels that each got.

#347 Add attribute to mark pNext pointers with the Vulkan struct they extend
  include/vk_mem_alloc.h
Labels: investigating

#345 cmake: always add vulkan headers dir
  CMakeLists.txt
  src/CMakeLists.txt
  src/cmake/install_target.cmake
Labels: investigating, quality

#341 cmake: correctly use find_dependency
  src/cmake/Config.cmake.in
Labels: input needed, quality
